// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package function

import (
	"context"

	"cloud.google.com/go/cloudtasks/apiv2"
	"cloud.google.com/go/secretmanager/apiv1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/api/idtoken"
)

// NewMockCloudTasksClientFactory creates a new instance of MockCloudTasksClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloudTasksClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloudTasksClientFactory {
	mock := &MockCloudTasksClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCloudTasksClientFactory is an autogenerated mock type for the cloudTasksClientFactory type
type MockCloudTasksClientFactory struct {
	mock.Mock
}

type MockCloudTasksClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloudTasksClientFactory) EXPECT() *MockCloudTasksClientFactory_Expecter {
	return &MockCloudTasksClientFactory_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function for the type MockCloudTasksClientFactory
func (_mock *MockCloudTasksClientFactory) NewClient(ctx context.Context) (*cloudtasks.Client, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 *cloudtasks.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*cloudtasks.Client, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *cloudtasks.Client); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudtasks.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudTasksClientFactory_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type MockCloudTasksClientFactory_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCloudTasksClientFactory_Expecter) NewClient(ctx any) *MockCloudTasksClientFactory_NewClient_Call {
	return &MockCloudTasksClientFactory_NewClient_Call{Call: _e.mock.On("NewClient", ctx)}
}

func (_c *MockCloudTasksClientFactory_NewClient_Call) Run(run func(ctx context.Context)) *MockCloudTasksClientFactory_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCloudTasksClientFactory_NewClient_Call) Return(client *cloudtasks.Client, err error) *MockCloudTasksClientFactory_NewClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockCloudTasksClientFactory_NewClient_Call) RunAndReturn(run func(ctx context.Context) (*cloudtasks.Client, error)) *MockCloudTasksClientFactory_NewClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretManagerClientFactory creates a new instance of MockSecretManagerClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretManagerClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretManagerClientFactory {
	mock := &MockSecretManagerClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretManagerClientFactory is an autogenerated mock type for the secretManagerClientFactory type
type MockSecretManagerClientFactory struct {
	mock.Mock
}

type MockSecretManagerClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretManagerClientFactory) EXPECT() *MockSecretManagerClientFactory_Expecter {
	return &MockSecretManagerClientFactory_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function for the type MockSecretManagerClientFactory
func (_mock *MockSecretManagerClientFactory) NewClient(ctx context.Context) (*secretmanager.Client, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 *secretmanager.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*secretmanager.Client, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *secretmanager.Client); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretmanager.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretManagerClientFactory_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type MockSecretManagerClientFactory_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSecretManagerClientFactory_Expecter) NewClient(ctx any) *MockSecretManagerClientFactory_NewClient_Call {
	return &MockSecretManagerClientFactory_NewClient_Call{Call: _e.mock.On("NewClient", ctx)}
}

func (_c *MockSecretManagerClientFactory_NewClient_Call) Run(run func(ctx context.Context)) *MockSecretManagerClientFactory_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSecretManagerClientFactory_NewClient_Call) Return(client *secretmanager.Client, err error) *MockSecretManagerClientFactory_NewClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockSecretManagerClientFactory_NewClient_Call) RunAndReturn(run func(ctx context.Context) (*secretmanager.Client, error)) *MockSecretManagerClientFactory_NewClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskTokenValidator creates a new instance of MockTaskTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskTokenValidator {
	mock := &MockTaskTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskTokenValidator is an autogenerated mock type for the taskTokenValidator type
type MockTaskTokenValidator struct {
	mock.Mock
}

type MockTaskTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskTokenValidator) EXPECT() *MockTaskTokenValidator_Expecter {
	return &MockTaskTokenValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockTaskTokenValidator
func (_mock *MockTaskTokenValidator) Validate(ctx context.Context, token string, audience string) (*idtoken.Payload, error) {
	ret := _mock.Called(ctx, token, audience)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *idtoken.Payload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*idtoken.Payload, error)); ok {
		return returnFunc(ctx, token, audience)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *idtoken.Payload); ok {
		r0 = returnFunc(ctx, token, audience)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idtoken.Payload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, token, audience)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskTokenValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTaskTokenValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - audience string
func (_e *MockTaskTokenValidator_Expecter) Validate(ctx any, token any, audience any) *MockTaskTokenValidator_Validate_Call {
	return &MockTaskTokenValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, token, audience)}
}

func (_c *MockTaskTokenValidator_Validate_Call) Run(run func(ctx context.Context, token string, audience string)) *MockTaskTokenValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskTokenValidator_Validate_Call) Return(payload *idtoken.Payload, err error) *MockTaskTokenValidator_Validate_Call {
	_c.Call.Return(payload, err)
	return _c
}

func (_c *MockTaskTokenValidator_Validate_Call) RunAndReturn(run func(ctx context.Context, token string, audience string) (*idtoken.Payload, error)) *MockTaskTokenValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstallationCredentialsResolver creates a new instance of MockInstallationCredentialsResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstallationCredentialsResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstallationCredentialsResolver {
	mock := &MockInstallationCredentialsResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstallationCredentialsResolver is an autogenerated mock type for the installationCredentialsResolver type
type MockInstallationCredentialsResolver struct {
	mock.Mock
}

type MockInstallationCredentialsResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstallationCredentialsResolver) EXPECT() *MockInstallationCredentialsResolver_Expecter {
	return &MockInstallationCredentialsResolver_Expecter{mock: &_m.Mock}
}

// GetInstallationCredentials provides a mock function for the type MockInstallationCredentialsResolver
func (_mock *MockInstallationCredentialsResolver) GetInstallationCredentials(ctx context.Context, owner string) (installationCredentials, error) {
	ret := _mock.Called(ctx, owner)

	if len(ret) == 0 {
		panic("no return value specified for GetInstallationCredentials")
	}

	var r0 installationCredentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (installationCredentials, error)); ok {
		return returnFunc(ctx, owner)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) installationCredentials); ok {
		r0 = returnFunc(ctx, owner)
	} else {
		r0 = ret.Get(0).(installationCredentials)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, owner)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInstallationCredentialsResolver_GetInstallationCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstallationCredentials'
type MockInstallationCredentialsResolver_GetInstallationCredentials_Call struct {
	*mock.Call
}

// GetInstallationCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
func (_e *MockInstallationCredentialsResolver_Expecter) GetInstallationCredentials(ctx any, owner any) *MockInstallationCredentialsResolver_GetInstallationCredentials_Call {
	return &MockInstallationCredentialsResolver_GetInstallationCredentials_Call{Call: _e.mock.On("GetInstallationCredentials", ctx, owner)}
}

func (_c *MockInstallationCredentialsResolver_GetInstallationCredentials_Call) Run(run func(ctx context.Context, owner string)) *MockInstallationCredentialsResolver_GetInstallationCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInstallationCredentialsResolver_GetInstallationCredentials_Call) Return(installationCredentialsMoqParam installationCredentials, err error) *MockInstallationCredentialsResolver_GetInstallationCredentials_Call {
	_c.Call.Return(installationCredentialsMoqParam, err)
	return _c
}

func (_c *MockInstallationCredentialsResolver_GetInstallationCredentials_Call) RunAndReturn(run func(ctx context.Context, owner string) (installationCredentials, error)) *MockInstallationCredentialsResolver_GetInstallationCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkflowJobStatusLookup creates a new instance of MockWorkflowJobStatusLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowJobStatusLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowJobStatusLookup {
	mock := &MockWorkflowJobStatusLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkflowJobStatusLookup is an autogenerated mock type for the workflowJobStatusLookup type
type MockWorkflowJobStatusLookup struct {
	mock.Mock
}

type MockWorkflowJobStatusLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowJobStatusLookup) EXPECT() *MockWorkflowJobStatusLookup_Expecter {
	return &MockWorkflowJobStatusLookup_Expecter{mock: &_m.Mock}
}

// GetWorkflowJobStatus provides a mock function for the type MockWorkflowJobStatusLookup
func (_mock *MockWorkflowJobStatusLookup) GetWorkflowJobStatus(ctx context.Context, owner string, repo string, jobID int64, credentials installationCredentials) (string, error) {
	ret := _mock.Called(ctx, owner, repo, jobID, credentials)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowJobStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, installationCredentials) (string, error)); ok {
		return returnFunc(ctx, owner, repo, jobID, credentials)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, installationCredentials) string); ok {
		r0 = returnFunc(ctx, owner, repo, jobID, credentials)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, installationCredentials) error); ok {
		r1 = returnFunc(ctx, owner, repo, jobID, credentials)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkflowJobStatusLookup_GetWorkflowJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowJobStatus'
type MockWorkflowJobStatusLookup_GetWorkflowJobStatus_Call struct {
	*mock.Call
}

// GetWorkflowJobStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - jobID int64
//   - credentials installationCredentials
func (_e *MockWorkflowJobStatusLookup_Expecter) GetWorkflowJobStatus(ctx any, owner any, repo any, jobID any, credentials any) *MockWorkflowJobStatusLookup_GetWorkflowJobStatus_Call {
	return &MockWorkflowJobStatusLookup_GetWorkflowJobStatus_Call{Call: _e.mock.On("GetWorkflowJobStatus", ctx, owner, repo, jobID, credentials)}
}

func (_c *MockWorkflowJobStatusLookup_GetWorkflowJobStatus_Call) Run(run func(ctx context.Context, owner string, repo string, jobID int64, credentials installationCredentials)) *MockWorkflowJobStatusLookup_GetWorkflowJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 installationCredentials
		if args[4] != nil {
			arg4 = args[4].(installationCredentials)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWorkflowJobStatusLookup_GetWorkflowJobStatus_Call) Return(s string, err error) *MockWorkflowJobStatusLookup_GetWorkflowJobStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockWorkflowJobStatusLookup_GetWorkflowJobStatus_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, jobID int64, credentials installationCredentials) (string, error)) *MockWorkflowJobStatusLookup_GetWorkflowJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRunnerVMCreator creates a new instance of MockRunnerVMCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunnerVMCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunnerVMCreator {
	mock := &MockRunnerVMCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunnerVMCreator is an autogenerated mock type for the runnerVMCreator type
type MockRunnerVMCreator struct {
	mock.Mock
}

type MockRunnerVMCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunnerVMCreator) EXPECT() *MockRunnerVMCreator_Expecter {
	return &MockRunnerVMCreator_Expecter{mock: &_m.Mock}
}

// CreateRunnerVM provides a mock function for the type MockRunnerVMCreator
func (_mock *MockRunnerVMCreator) CreateRunnerVM(ctx context.Context, event WorkflowJobEvent, labels *RunnerLabels, credentials installationCredentials) error {
	ret := _mock.Called(ctx, event, labels, credentials)

	if len(ret) == 0 {
		panic("no return value specified for CreateRunnerVM")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, WorkflowJobEvent, *RunnerLabels, installationCredentials) error); ok {
		r0 = returnFunc(ctx, event, labels, credentials)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunnerVMCreator_CreateRunnerVM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRunnerVM'
type MockRunnerVMCreator_CreateRunnerVM_Call struct {
	*mock.Call
}

// CreateRunnerVM is a helper method to define mock.On call
//   - ctx context.Context
//   - event WorkflowJobEvent
//   - labels *RunnerLabels
//   - credentials installationCredentials
func (_e *MockRunnerVMCreator_Expecter) CreateRunnerVM(ctx any, event any, labels any, credentials any) *MockRunnerVMCreator_CreateRunnerVM_Call {
	return &MockRunnerVMCreator_CreateRunnerVM_Call{Call: _e.mock.On("CreateRunnerVM", ctx, event, labels, credentials)}
}

func (_c *MockRunnerVMCreator_CreateRunnerVM_Call) Run(run func(ctx context.Context, event WorkflowJobEvent, labels *RunnerLabels, credentials installationCredentials)) *MockRunnerVMCreator_CreateRunnerVM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 WorkflowJobEvent
		if args[1] != nil {
			arg1 = args[1].(WorkflowJobEvent)
		}
		var arg2 *RunnerLabels
		if args[2] != nil {
			arg2 = args[2].(*RunnerLabels)
		}
		var arg3 installationCredentials
		if args[3] != nil {
			arg3 = args[3].(installationCredentials)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRunnerVMCreator_CreateRunnerVM_Call) Return(err error) *MockRunnerVMCreator_CreateRunnerVM_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunnerVMCreator_CreateRunnerVM_Call) RunAndReturn(run func(ctx context.Context, event WorkflowJobEvent, labels *RunnerLabels, credentials installationCredentials) error) *MockRunnerVMCreator_CreateRunnerVM_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRunnerVMDeleter creates a new instance of MockRunnerVMDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunnerVMDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunnerVMDeleter {
	mock := &MockRunnerVMDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunnerVMDeleter is an autogenerated mock type for the runnerVMDeleter type
type MockRunnerVMDeleter struct {
	mock.Mock
}

type MockRunnerVMDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunnerVMDeleter) EXPECT() *MockRunnerVMDeleter_Expecter {
	return &MockRunnerVMDeleter_Expecter{mock: &_m.Mock}
}

// DeleteRunnerVM provides a mock function for the type MockRunnerVMDeleter
func (_mock *MockRunnerVMDeleter) DeleteRunnerVM(ctx context.Context, name string, labels *RunnerLabels) error {
	ret := _mock.Called(ctx, name, labels)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRunnerVM")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *RunnerLabels) error); ok {
		r0 = returnFunc(ctx, name, labels)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunnerVMDeleter_DeleteRunnerVM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRunnerVM'
type MockRunnerVMDeleter_DeleteRunnerVM_Call struct {
	*mock.Call
}

// DeleteRunnerVM is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - labels *RunnerLabels
func (_e *MockRunnerVMDeleter_Expecter) DeleteRunnerVM(ctx any, name any, labels any) *MockRunnerVMDeleter_DeleteRunnerVM_Call {
	return &MockRunnerVMDeleter_DeleteRunnerVM_Call{Call: _e.mock.On("DeleteRunnerVM", ctx, name, labels)}
}

func (_c *MockRunnerVMDeleter_DeleteRunnerVM_Call) Run(run func(ctx context.Context, name string, labels *RunnerLabels)) *MockRunnerVMDeleter_DeleteRunnerVM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *RunnerLabels
		if args[2] != nil {
			arg2 = args[2].(*RunnerLabels)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRunnerVMDeleter_DeleteRunnerVM_Call) Return(err error) *MockRunnerVMDeleter_DeleteRunnerVM_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunnerVMDeleter_DeleteRunnerVM_Call) RunAndReturn(run func(ctx context.Context, name string, labels *RunnerLabels) error) *MockRunnerVMDeleter_DeleteRunnerVM_Call {
	_c.Call.Return(run)
	return _c
}
