name: Test gcrunner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: gcrunner=${{ github.run_id }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - name: Hello
        run: echo "Hello from gcrunner!"

  test-ubuntu22:
    runs-on: gcrunner=${{ github.run_id }}-u22/image=ubuntu22-full-x64
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - name: Hello
        run: echo "Hello from gcrunner on Ubuntu 22.04!"
      - name: Check OS
        run: lsb_release -a
